FROM ruby:3.1-slim
RUN apt-get update && apt-get install curl gnupg build-essential libpq-dev git -y
# Fix incompatiable node version for turbo
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq
RUN apt install yarn -y
RUN gem install bundler
WORKDIR /app


