version: '2'

services:
  # delete once app was created
  builder:
    build:
      context: ./
      dockerfile: Dockerfile_builder
    command: sh -c 'cd /app/ && gem install rails -v "~>7" && rails new -d=postgresql --css sass -j esbuild .'
    volumes:
      - .:/app/
      - bundler_gems:/usr/local/bundle/
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis
    command: redis-server --appendonly yes

  postgres:
    image: postgres:10.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5439}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}

  app: &app
    tty: true
    build:
      target: development
      context: .
    command: sh -c 'yarn install && bundle install && ./bin/dev'
    #env_file: .env
    volumes:
      - .:/app/
      - bundler_gems:/usr/local/bundle/
      - node_modules:/app/node_modules
    depends_on:
      - postgres
      - redis
    environment:
      BINDING: '0.0.0.0'
    ports:
      - 3000:3000

  test:
    <<: *app
    command: sh -c 'bundle exec rspec'
    environment:
      RAILS_ENV: test

volumes:
  bundler_gems:
  postgres_data:
  redis_data:
  node_modules:
